kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  annotations:
    app.openshift.io/vcs-ref: main
    app.openshift.io/vcs-uri: 'https://github.com/MoOyeg/RHACS-Kenna-Integration.git'
  name: rhacs-kenna-tool
  namespace: rhacs-kenna-tool
  labels:
    app: rhacs-kenna-tool
    app.kubernetes.io/component: rhacs-kenna-tool
    app.kubernetes.io/instance: rhacs-kenna-tool
    app.kubernetes.io/name: rhacs-kenna-tool
    app.kubernetes.io/part-of: rhacs-kenna-tool
spec:
  output:
    to:
      kind: ImageStreamTag
      name: 'rhacs-kenna-tool:latest'
  resources: {}
  successfulBuildsHistoryLimit: 5
  failedBuildsHistoryLimit: 5
  strategy:
    type: Docker
    dockerStrategy:
      dockerfilePath: Dockerfile
  postCommit: {}
  source:
    type: Git
    git:
      uri: 'https://github.com/MoOyeg/RHACS-Kenna-Integration.git'
      ref: main
    contextDir: /
  triggers:
    - type: ConfigChange
  runPolicy: Serial